/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AvatarStack: typeof import('./src/components/AvatarStack.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BurndownChart: typeof import('./src/components/BurndownChart.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    CompleteSprintDialog: typeof import('./src/components/CompleteSprintDialog.vue')['default']
    ConfirmHost: typeof import('./src/components/ConfirmHost.vue')['default']
    CreateIssueDialog: typeof import('./src/components/CreateIssueDialog.vue')['default']
    CreateProjectDialog: typeof import('./src/components/CreateProjectDialog.vue')['default']
    CreateWorkspaceDialog: typeof import('./src/components/CreateWorkspaceDialog.vue')['default']
    Donut: typeof import('./src/components/Donut.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LabelChip: typeof import('./src/components/LabelChip.vue')['default']
    LivePill: typeof import('./src/components/LivePill.vue')['default']
    LogTimeDialog: typeof import('./src/components/LogTimeDialog.vue')['default']
    MultiSelectPopover: typeof import('./src/components/MultiSelectPopover.vue')['default']
    NativeSelect: typeof import('./src/components/NativeSelect.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PriorityBars: typeof import('./src/components/PriorityBars.vue')['default']
    ProjectSettingsDialog: typeof import('./src/components/ProjectSettingsDialog.vue')['default']
    QuickAdd: typeof import('./src/components/QuickAdd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./src/components/SelectField.vue')['default']
    SprintBar: typeof import('./src/components/SprintBar.vue')['default']
    SprintReview: typeof import('./src/components/SprintReview.vue')['default']
    StartSprintDialog: typeof import('./src/components/StartSprintDialog.vue')['default']
    StatusDot: typeof import('./src/components/StatusDot.vue')['default']
    TaskDrawer: typeof import('./src/components/TaskDrawer.vue')['default']
    TimesheetLogDialog: typeof import('./src/components/TimesheetLogDialog.vue')['default']
    TweaksPanel: typeof import('./src/components/TweaksPanel.vue')['default']
    ViewControls: typeof import('./src/components/ViewControls.vue')['default']
  }
}
