// Curated, tree-shakeable icon registry. Importing the whole lucide-vue-next
// namespace (`import * as lucide`) pulled the entire ~800KB icon set into the
// bundle. This maps only the icons the app actually references (static usages +
// the project/workspace icon pickers) so the rest is dropped at build time.
//
// To add an icon: add its kebab name below with a matching named import.
import {
	Activity,
	ArrowRight,
	ArrowRightLeft,
	AtSign,
	BarChart3,
	Bell,
	Bookmark,
	Box,
	Briefcase,
	Bug,
	Building,
	Calendar,
	CalendarRange,
	Check,
	CheckCheck,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronsUpDown,
	CircleCheckBig,
	CircleDot,
	Clock,
	Columns3,
	Copy,
	CreditCard,
	Download,
	Ellipsis,
	ExternalLink,
	File,
	FileText,
	Folder,
	GanttChart,
	Gauge,
	GitPullRequest,
	Globe,
	GripVertical,
	History,
	Inbox,
	Layers,
	Link2,
	ListChecks,
	ListFilter,
	Loader,
	Map,
	Megaphone,
	MessageSquare,
	Microscope,
	Minus,
	Moon,
	PanelLeft,
	Paperclip,
	Pencil,
	Plus,
	Rocket,
	RotateCcw,
	Search,
	Server,
	Settings,
	SlidersHorizontal,
	Smartphone,
	SmilePlus,
	Sparkles,
	Square,
	SquareCheckBig,
	SquarePen,
	SquarePlus,
	Star,
	Sun,
	Tag,
	Target,
	Timer,
	Trash2,
	Undo2,
	User,
	UserPlus,
	Users,
	Wallet,
	X,
} from 'lucide-vue-next'

export const ICONS = {
	activity: Activity,
	'arrow-right': ArrowRight,
	'arrow-right-left': ArrowRightLeft,
	'at-sign': AtSign,
	'bar-chart-3': BarChart3,
	bell: Bell,
	bookmark: Bookmark,
	box: Box,
	briefcase: Briefcase,
	bug: Bug,
	building: Building,
	calendar: Calendar,
	'calendar-range': CalendarRange,
	check: Check,
	'check-check': CheckCheck,
	'chevron-down': ChevronDown,
	'chevron-left': ChevronLeft,
	'chevron-right': ChevronRight,
	'chevrons-up-down': ChevronsUpDown,
	'circle-check-big': CircleCheckBig,
	'circle-dot': CircleDot,
	clock: Clock,
	'columns-3': Columns3,
	copy: Copy,
	'credit-card': CreditCard,
	download: Download,
	ellipsis: Ellipsis,
	'external-link': ExternalLink,
	file: File,
	'file-text': FileText,
	folder: Folder,
	'gantt-chart': GanttChart,
	gauge: Gauge,
	'git-pull-request': GitPullRequest,
	globe: Globe,
	'grip-vertical': GripVertical,
	history: History,
	inbox: Inbox,
	layers: Layers,
	'link-2': Link2,
	'list-checks': ListChecks,
	'list-filter': ListFilter,
	loader: Loader,
	map: Map,
	megaphone: Megaphone,
	'message-square': MessageSquare,
	microscope: Microscope,
	minus: Minus,
	moon: Moon,
	'panel-left': PanelLeft,
	paperclip: Paperclip,
	pencil: Pencil,
	plus: Plus,
	rocket: Rocket,
	'rotate-ccw': RotateCcw,
	search: Search,
	server: Server,
	settings: Settings,
	'sliders-horizontal': SlidersHorizontal,
	smartphone: Smartphone,
	'smile-plus': SmilePlus,
	sparkles: Sparkles,
	square: Square,
	'square-check-big': SquareCheckBig,
	'square-pen': SquarePen,
	'square-plus': SquarePlus,
	star: Star,
	sun: Sun,
	tag: Tag,
	target: Target,
	timer: Timer,
	'trash-2': Trash2,
	'undo-2': Undo2,
	user: User,
	'user-plus': UserPlus,
	users: Users,
	wallet: Wallet,
	x: X,
}

export const FALLBACK_ICON = Square
